name: HaisuuPiece
version: '1.0-SNAPSHOT'
main: br.com.haisuu.haisuupiece.Main
api-version: '1.16'

commands:
  textura:
    description: Envia o link da textura
    aliases:
      - texture
      - resource
      - resourcepack
      - rp
      - texturepack
    permission: hp.basic
    permission-message: You do not have permission!
    usage: /<command>
  discord:
    description: Envia o link do discord
    aliases:
      - disc
      - dc
    permission: hp.basic
    permission-message: You do not have permission!
    usage: /<command>
  site:
    description: Envia o link do site
    aliases:
      - website
    permission: hp.basic
    permission-message: You do not have permission!
    usage: /<command>
  hp:
    description: Comando para administradores e gerentes
    aliases:
      - haisuupiece
      - haisuup
      - hpiece
    permission: hp.admin
    permission-message: You do not have permission!
    usage: /hp <subcommand>